jobs:
  workflow:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Startup
        uses: actions/checkout@v2
      - name: Install Prerequisites
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Unit Tests
        run: ./verify/main

name: Ci

on:
  schedule:
    - cron: "0 */6 * * *"
